#spring.application.name=fswd-sbapp
# properites
#server.port = 8081

# yml
spring:
  application:
    name: fswd-sbapp
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/production_db
    username: danadorn
    password: 123
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /istad